//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototyp2.Views
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CmentarzEntities : DbContext
    {
        public CmentarzEntities()
            : base("name=CmentarzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<grob> grob { get; set; }
        public virtual DbSet<groby_rodzaj> groby_rodzaj { get; set; }
        public virtual DbSet<kaplan> kaplan { get; set; }
        public virtual DbSet<miejscowosc> miejscowosc { get; set; }
        public virtual DbSet<osoba> osoba { get; set; }
        public virtual DbSet<osoba_typ> osoba_typ { get; set; }
    }
}
