//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototyp2.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class grob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public grob()
        {
            this.osoba = new HashSet<osoba>();
        }
    
        public int id_grob { get; set; }
        public int groby_rodzaj_id { get; set; }
        public string koordynaty { get; set; }
        public int miejscowosc_id { get; set; }
    
        public virtual groby_rodzaj groby_rodzaj { get; set; }
        public virtual miejscowosc miejscowosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<osoba> osoba { get; set; }
    }
}
