//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototyp2.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class osoba
    {
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string nazwisko_rodowe { get; set; }
        public System.DateTime data_zgonu { get; set; }
        public System.DateTime data_urodzenia { get; set; }
        public int grob_id { get; set; }
        public Nullable<int> osoba_typ_id { get; set; }
        public Nullable<int> kaplan_id { get; set; }
    
        public virtual grob grob { get; set; }
        public virtual kaplan kaplan { get; set; }
        public virtual osoba_typ osoba_typ { get; set; }
    }
}
